name: '${name}'
version: '${version}-${gitCommit}'
main: tech.qhuyy.insureinv.InsureInv
api-version: '1.21'
folia-supported: true
authors: [ birri ]
website: https://qhuyy.tech/
description: Inventory protection plugin with economy integration

softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI

libraries:
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0
  - com.zaxxer:HikariCP:5.1.0
  - net.kyori:adventure-api:4.26.1
  - net.kyori:adventure-text-minimessage:4.26.1
  - net.kyori:adventure-platform-bukkit:4.4.1

commands:
  insureinv:
    description: Main InsureInv command
    usage: /<command> <buy|toggle|info|usage|config|help> [args]
    aliases:
      - inv
      - hinv

permissions:
  insureinv.use:
    description: Allows using basic InsureInv commands
    default: true
  insureinv.admin:
    description: Allows using administrative InsureInv commands
    default: op
    children:
      insureinv.use: true
